### ISSUE TITLE
Custom help command is conflicted with default help command

### ISSUE THREAD

**Issue by Iqrar99** [intrepidbird/psyduck#5]
On this PR #2, It implemented custom help command without disabling the default help command on bot base. Thus this error will be raised if you run the bot
```bash
$ python main.py 
Traceback (most recent call last):
  File "D:\Documents\Github\psyduck\main.py", line 75, in <module>
    async def help_command(ctx):
  File "D:\Documents\Github\psyduck\env\lib\site-packages\discord\ext\commands\core.py", line 1521, in decorator
    self.add_command(result)
  File "D:\Documents\Github\psyduck\env\lib\site-packages\discord\ext\commands\bot.py", line 246, in add_command
    super().add_command(command)
  File "D:\Documents\Github\psyduck\env\lib\site-packages\discord\ext\commands\core.py", line 1356, in add_command
    raise CommandRegistrationError(command.name)
discord.ext.commands.errors.CommandRegistrationError: The command help is already an existing command or alias.
```

### Solution proposed
Make a class `PsyduckHelpCommand` class that inherit [this](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=commands%20minimalhelpcommand#helpcommand), then we assign it into bot client
```py
bot.help_command = PsyduckHelpCommand()
```

**Comment by Iqrar99** [comment]
Can you elaborate? Disable custom help command means you want to delete the function?
https://github.com/intrepidbird/psyduck/blob/601084aebd31cf50df89a5b5d96f39d1f38f2790/main.py#L71-L78

**Comment by intrepidbird** [comment]
What do you recommend? Should we delete the default command instead (or override it somehow )

**Comment by Iqrar99** [comment]
There are 2 ways to do it
1. Disable the default help command and let it replaced by the custom help command because they have the same command name. So it can avoid the conflict.
2. Make a class `PsyduckHelpCommand` class that inherit [this](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=commands%20minimalhelpcommand#helpcommand), then we assign it into bot client
```py
bot.help_command = PsyduckHelpCommand()
```

**Comment by intrepidbird** [comment]
OK, please make a PR for that :smile:
